import React from 'react'
import { Titlebar } from './Titlebar'
import Sidebar from './Sidebar'
import Footer from './Footer'
import { useRouter } from 'next/router'
import styles from "@/styles/Layout.module.css";
import Head from 'next/head'
import Explorer from './Explorer'

const Layout = ({ children }) => {
    const router = useRouter()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Titlebar />
            <div className={styles.main}>
                <Sidebar />
                <Explorer />
                {children}
            </div>
            <Footer />
        </>
    )
}

export default Layout