import React, { useEffect, useState } from "react";
import { Titlebar } from "./Titlebar";
import Sidebar from "./Sidebar";
import Footer from "./Footer";
import { useRouter } from "next/router";
import styles from "@/styles/Layout.module.css";
import Head from "next/head";
import Explorer from "./Explorer";
import Quote from "./Quote";
import { FaReact } from "react-icons/fa";
import { FaHtml5 } from "react-icons/fa";
import { FaCss3 } from "react-icons/fa";
import { FaJs } from "react-icons/fa";
import { VscMarkdown } from "react-icons/vsc";
import Tabsbar from "./Tabsbar";
import MusicPlayer from "./MusicPlayer";


const explorerItems = [
  {
    name: "home.jsx",
    path: "/",
    Icon: FaReact,
    class: styles.react
  },
  {
    name: "about.html",
    path: "/about",
    Icon: FaHtml5,
    class: styles.html
  },
  {
    name: "contact.css",
    path: "/contact",
    Icon: FaCss3,
    class: styles.css
  },
  {
    name: "projects.js",
    path: "/projects",
    Icon: FaJs,
    class: styles.js
  },
  {
    name: "github.md",
    path: "/github",
    Icon: VscMarkdown,
    class: styles.md
  },
];

const Layout = ({ children }) => {
  const router = useRouter();
  const [quoteVisible, setQuoteVisible] = useState(true);
  const [playerVisible, setPlayerVisible] = useState(false);

  const showQuote = () => {
    setQuoteVisible(true);
    setPlayerVisible(false);
  };

  const hideQuote = () => {
    setQuoteVisible(false);
  };

  const showPlayer = () => {
    setPlayerVisible(true);
    setQuoteVisible(false);
  };

  const hidePlayer = () => {
    setPlayerVisible(false);
  };

  const togglePlayer = () => {
    playerVisible ? hidePlayer() : showPlayer();
  }

  const toggleQuote = () => {
    quoteVisible ? hideQuote() : showQuote();
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Titlebar />
      <div className={styles.main}>
        <Sidebar />
        <Explorer explorerItems={explorerItems} />
        <div style={{ width: '100%' }}>
          <Tabsbar items={explorerItems} />
          <main id="main-editor" className={styles.content}>
            {children}
          </main>
        </div>
      </div>
      {quoteVisible && <Quote showQuote={showQuote} hideQuote={hideQuote} />}
      {playerVisible && <MusicPlayer showPlayer={showPlayer} hidePlayer={hidePlayer} />}
      <Footer quoteVisible={quoteVisible} playerVisible={playerVisible} toggleQuote={toggleQuote} togglePlayer={togglePlayer} />
    </>
  );
};

export default Layout;
